"""seed changes

Revision ID: 2aa0a02662fd
Revises: 98c615bc9b11
Create Date: 2026-03-11 11:56:13.634667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2aa0a02662fd'
down_revision: Union[str, Sequence[str], None] = '98c615bc9b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # remove old many-to-many role table
    op.drop_table('user_roles')

    # drop unused updated_at columns
    op.drop_column('orders', 'updated_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('roles', 'updated_at')

    # STEP 1: add role_id as nullable first
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))

    # STEP 2: create FK
    op.create_foreign_key(
        "fk_users_role",
        "users",
        "roles",
        ["role_id"],
        ["id"]
    )

    # STEP 3: assign default role to existing users
    op.execute("""
        UPDATE users
        SET role_id = (
            SELECT id FROM roles WHERE name = 'user' LIMIT 1
        )
        WHERE role_id IS NULL
    """)

    # STEP 4: enforce NOT NULL after data is populated
    op.alter_column("users", "role_id", nullable=False)

    # remove updated_at column
    op.drop_column('users', 'updated_at')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('permissions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_roles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    # ### end Alembic commands ###
